### PR TITLE
spaCy v2.0.12

### PR DESCRIPTION
**Pull request by honnibal**

### CODE REVIEW

**Comment by honnibal** [comment]
YAML is exasperating. @ines or @rmax , any idea why the `recipe-maintainers` apparently isn't parsing as a json list here? It looks right to me!

**Comment by danielfrg** [comment]
Very weird. I  can read the yaml in a parser so probably an error on the linter?

**Comment by honnibal** [comment]
Open to suggestions!

I guess we merge even if linting fails?

**Comment by danielfrg** [comment]
I am ok with that. Could you change the recipe to add the installtion via pip: https://conda-forge.org/docs/meta.html#use-pip

**Comment by honnibal** [comment]
@rmax hm, I ran

```
conda install -c conda-forge conda-smithy 
conda smithy regenerate
```

Was this incorrect?

**Comment by rmax** [comment]
@honnibal that is.

Appveyor was fixed but linux builds fail with:
```
+ setup_conda_rc /home/conda/feedstock_root /home/conda/recipe_root /home/conda/feedstock_root/.ci_support/linux_python3.5.yaml
--- Logging error ---
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/conda/cli/main_config.py", line 30, in execute
    execute_config(args, parser)
  File "/opt/conda/lib/python3.6/site-packages/conda/cli/main_config.py", line 263, in execute_config
    raise CouldntParseError("key %r should be a list, not %s." % (key, bad))
conda.exceptions.CouldntParseError: key 'channels' should be a list, not CommentedSeq.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "/opt/conda/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/opt/conda/lib/python3.6/site-packages/conda/cli/main_config.py", line 32, in execute
    raise CondaError(e)
conda.CondaError: <unprintable CondaError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/conda/__init__.py", line 48, in __str__
    return text_type(self.message % self._kwargs)
TypeError: unsupported operand type(s) for %: 'CouldntParseError' and 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/conda/gateways/logging.py", line 64, in emit
    msg = self.format(record)
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 839, in format
    return fmt.format(record)
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 576, in format
    record.message = record.getMessage()
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
  File "/opt/conda/lib/python3.6/site-packages/conda/__init__.py", line 44, in __repr__
    return '%s: %s' % (self.__class__.__name__, text_type(self))
  File "/opt/conda/lib/python3.6/site-packages/conda/__init__.py", line 56, in __str__
    "",
TypeError: sequence item 2: expected str instance, CouldntParseError found
Call stack:
  File "/opt/conda/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda/cli/main.py", line 113, in main
    return conda_exception_handler(_main, *args)
  File "/opt/conda/lib/python3.6/site-packages/conda/exceptions.py", line 1108, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda/exceptions.py", line 822, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/opt/conda/lib/python3.6/site-packages/conda/exceptions.py", line 849, in handle_exception
    return self.handle_application_exception(exc_val, exc_tb)
  File "/opt/conda/lib/python3.6/site-packages/conda/exceptions.py", line 865, in handle_application_exception
    self._print_conda_exception(exc_val, exc_tb)
  File "/opt/conda/lib/python3.6/site-packages/conda/exceptions.py", line 869, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "/opt/conda/lib/python3.6/site-packages/conda/exceptions.py", line 800, in print_conda_exception
    stderrlog.info("\n%r\n", exc_val)
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 1307, in info
    self._log(INFO, msg, args, **kwargs)
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 1443, in _log
    self.handle(record)
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 1453, in handle
    self.callHandlers(record)
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 1515, in callHandlers
    hdlr.handle(record)
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 864, in handle
    self.emit(record)
  File "/opt/conda/lib/python3.6/site-packages/conda/gateways/logging.py", line 73, in emit
    self.handleError(record)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
Traceback (most recent call last):
  File "/opt/conda/bin/setup_conda_rc", line 11, in <module>
    sys.exit(setup_conda_rc())
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_forge_ci_setup/build_utils.py", line 62, in setup_conda_rc
    call(["conda", "config", "--add", "channels", c])
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'config', '--add', 'channels', 'defaults']' returned non-zero exit status 1.
Exited with code 1
```

@danielfrg @jakirkham any idea how to fix this?

**Comment by honnibal** [comment]
:tada: 
I guess switching to the preferred pip style fixed it. Still don't understand the previous error, but shrug!

@rmax Should be good to merge right?

**Comment by rmax** [comment]
@honnibal looks good to me!

I had to make a manual merge due to conflicts, commits were not in the same order due to divergence between your `master` and `conda-forge:master` branch. I'd suggest to always start from a fresh checkout from the recipe's `master` branch.

**Comment by rmax** [comment]
An OSX build required a restart. After that all builds finished successfully. 🎉

**Pull request merged**
