### PR TITLE
2.2.4

### PR DESCRIPTION
**Pull request by rmax**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rmax** [comment]
@adrianeboyd the additional commit in this PR fixes the importlib issue.

However there are tests failing in win. Maybe you can take a look at it!

**Comment by rmax** [comment]
Looks like we need to skip `tests\regression\test_issue4725.py`. Maybe @ines or @honnibal can tell if this is related to the other multiprocessing issue in win and whether if it's safe to skip that test.

**Comment by adrianeboyd** [comment]
All the windows multiprocessing tests failed. I don't want to skip these tests and it looks like it's just a matter of how pytest is being called in the CI, since these tests pass in our CI for windows.

**Comment by rmax** [comment]
Fixed in #76.

**Pull request closed without merging**
