### PR TITLE
Update for v2.2.4

### PR DESCRIPTION
**Pull request by adrianeboyd**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
@conda-forge-admin, please rerender

**Comment by adrianeboyd** [comment]
@conda-forge-admin, please restart ci

**Comment by rmax** [comment]
I took a look and it seems there is an issue with `catalogue`:
```
❯ rg '>=0.20' ./build_artifacts
build_artifacts/spacy_1589319418983/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.7/site-packages/catalogue-1.0.0.dist-info/METADATA
28:Requires-Dist: importlib-metadata (>=0.20) ; python_version < "3.8"

build_artifacts/spacy_1589319418983/_build_env/lib/python3.8/site-packages/catalogue-1.0.0.dist-info/METADATA
28:Requires-Dist: importlib-metadata (>=0.20) ; python_version < "3.8"
```

Also defined here https://github.com/conda-forge/catalogue-feedstock/blob/master/recipe/meta.yaml#L22

According to this traceback
```
    Preparing wheel metadata: started
    ERROR: Could not find a version that satisfies the requirement importlib-metadata>=0.20 (from versions: none)
    ERROR: No matching distribution found for importlib-metadata>=0.20
    Traceback (most recent call last):
      File "/home/conda/feedstock_root/build_artifacts/spacy_1589319418983/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/home/conda/feedstock_root/build_artifacts/spacy_1589319418983/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/conda/feedstock_root/build_artifacts/spacy_1589319418983/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpp1_764e5', '--quiet', 'importlib-metadata>=0.20']' returned non-zero exit status 1.
```

`pip wheel` cannot find the `importlib-metadata>=0.20` which should be already there. For some reason it cannot find it.

**Comment by adrianeboyd** [comment]
@rmax Thanks for taking a look!

I added that dependency to `catalogue` yesterday and a created a new build for it, incrementing the build number, but it doesn't seem to necessarily be chosen over build 0 by the CI. In one CI test yesterday it did choose build 1 in linux and that build passed, but I'm not sure why the other builds keep choosing build 0.

For example, there is build 1, but here, build 0 is selected:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=160381&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=937c195f-508d-5135-dc9f-d4b5730df0f7&l=433

Would it be necessary to release it with a new version number?

**Comment by rmax** [comment]
🎉

**Pull request merged**
